

const Dashboard = () => {
  return (
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a purus id ante sagittis fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus enim ipsum, facilisis et risus ac, luctus dapibus massa. Fusce porta augue ac augue porttitor cursus. Nullam eget dapibus dolor, vitae pretium sem. Nam et maximus lectus. Proin lacinia dui tortor.

    Ut nec libero ac velit blandit mattis. Maecenas vitae tincidunt justo. Etiam sit amet enim dui. Suspendisse ultrices eu est sit amet pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris gravida enim vitae risus fringilla, condimentum viverra lectus mollis. Pellentesque tempor urna elit, iaculis vestibulum metus semper ut. Morbi rhoncus congue sapien vel placerat. Quisque tempor molestie facilisis. Nullam diam velit, sodales non nisi ac, lobortis commodo odio. Nulla accumsan congue diam, ac luctus est pulvinar at. Suspendisse vel luctus sapien, malesuada blandit purus. Quisque facilisis est vel ligula condimentum, ac auctor tellus molestie. Vestibulum nec sem commodo, euismod libero sit amet, mollis augue. Maecenas euismod bibendum velit, in pretium eros lobortis vel.
    
    Maecenas pharetra eleifend magna a venenatis. Praesent egestas est ex, sed tristique augue pretium semper. Phasellus vitae orci sodales, vehicula enim quis, malesuada tellus. Pellentesque nec luctus dui. Aliquam eu nunc dui. Donec eleifend mattis est sed viverra. Nulla ac eros massa. Suspendisse ut felis sit amet leo pretium malesuada dignissim vel dolor. Mauris et odio at tortor bibendum eleifend. Maecenas diam nibh, consequat quis tellus eget, rhoncus cursus nisl. Sed mattis enim vitae tortor dignissim, ut venenatis diam pulvinar. Curabitur nec arcu et elit laoreet congue. Phasellus vitae vestibulum ipsum. Duis imperdiet est quis leo rutrum pretium ut id purus. Morbi quis commodo erat, ut maximus sapien. Donec blandit dui sem.
    
    Donec non justo et arcu volutpat venenatis. Donec euismod, sapien at blandit vestibulum, nisi nisi tincidunt velit, sed varius nisl ante eget enim. Etiam nec neque non mi aliquet mattis quis sit amet leo. Vivamus id pretium magna. Suspendisse aliquet tincidunt pellentesque. Integer et placerat nunc. Pellentesque quis facilisis mi, a finibus ex. Ut mauris neque, tristique quis euismod ac, consequat ac metus. Quisque egestas sapien felis, tempor pretium eros pretium sit amet. Cras sit amet laoreet lectus. Duis ac enim nec ipsum scelerisque ullamcorper id non tortor. In vestibulum mauris justo, id faucibus diam aliquet ut. Ut ut volutpat lacus, in finibus ipsum.
    
    Mauris auctor mauris ac nisi euismod tincidunt. Morbi ut pretium velit. Nam dolor nulla, mollis a neque sit amet, efficitur molestie purus. Etiam vel erat quis felis venenatis venenatis. Nam venenatis elit et aliquam commodo. Curabitur viverra nulla in velit ultricies, et lacinia est pellentesque. Cras ac aliquam felis.
    
    Nulla cursus pulvinar eleifend. Vivamus a velit consectetur, volutpat libero nec, lacinia magna. Proin metus risus, fermentum eu neque at, vulputate commodo lacus. Ut at metus a ex rutrum tincidunt faucibus non neque. Sed a eleifend ante, ut euismod quam. Nam vehicula massa ante, non placerat massa egestas id. Cras eget odio sollicitudin, placerat lacus et, bibendum mi. Aliquam dignissim posuere lacus, sit amet dapibus sem viverra sed. Etiam tincidunt venenatis diam at viverra. Nullam rutrum diam at turpis euismod efficitur. Nulla sed orci vestibulum, blandit lectus non, porttitor nunc. Curabitur imperdiet porttitor feugiat. Sed quis hendrerit risus, quis maximus velit. Quisque eget nunc nec ex aliquet blandit.
    
    Pellentesque id facilisis sapien, at porta ante. Suspendisse potenti. Pellentesque ultrices iaculis nunc ut porta. Aenean tristique ac est et elementum. Integer convallis enim nunc. Quisque sit amet elementum massa, a iaculis ligula. Donec elementum lorem turpis, eget mattis nibh sodales vel. Nunc a posuere neque, et vestibulum nisl. Integer hendrerit rhoncus lectus pharetra porttitor.
    
    Mauris ipsum risus, rutrum nec ullamcorper ut, posuere sit amet dolor. Integer eu nulla eros. Fusce sed est sed augue finibus posuere a et felis. Donec viverra posuere consectetur. Donec a ultricies elit, vitae malesuada augue. Ut maximus, erat eu efficitur ullamcorper, tellus orci malesuada nibh, nec viverra nulla ante ultrices turpis. Nam quis tortor metus. Sed et eros aliquam, volutpat tellus et, hendrerit urna. Ut aliquet eros augue, a posuere ante porttitor nec. Duis sit amet felis nec quam suscipit maximus non a nibh. Maecenas consectetur mauris quam, quis ultricies nisl fermentum sed. Cras imperdiet non mauris sed posuere. Nulla fermentum dolor tincidunt, scelerisque justo at, porta enim. Nam est mauris, consequat at lorem at, vestibulum vehicula orci.
    
    Morbi rhoncus vel dui eget convallis. Aenean vitae turpis laoreet urna posuere feugiat nec vel lectus. Fusce ultricies fringilla odio quis imperdiet. Quisque hendrerit pulvinar dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum malesuada scelerisque. Curabitur quis ante quis orci rutrum hendrerit vitae et turpis.
    
    Maecenas tincidunt risus quis purus fringilla, id varius velit faucibus. Quisque vel ornare quam. Nulla rutrum eget leo ullamcorper ornare. Donec euismod malesuada dapibus. Nam ultrices tempus mi vel porta. Donec lobortis elit et neque egestas, vitae efficitur mi posuere. Nulla at porta massa. Aenean hendrerit, magna eget gravida accumsan, risus sapien faucibus mauris, sit amet ullamcorper mauris nisi a est. Mauris aliquet dignissim metus eget cursus.
    
    Cras enim odio, semper eu nibh efficitur, pretium pulvinar arcu. Pellentesque porta vulputate nisl. Etiam ac eros quis leo mattis interdum eget sit amet nunc. Suspendisse ligula tellus, eleifend non tellus quis, venenatis varius libero. Curabitur ut risus nibh. Sed quam sem, tristique sed tellus ut, mollis rhoncus lectus. Curabitur ex arcu, congue non lobortis scelerisque, elementum a nibh. Etiam ultrices enim lectus. Phasellus odio arcu, pharetra a vehicula at, venenatis non odio. Suspendisse arcu turpis, volutpat id lorem ac, viverra scelerisque diam. Curabitur semper feugiat feugiat.
    
    Praesent pharetra suscipit diam elementum suscipit. Nunc quam massa, suscipit sed lacus sit amet, tincidunt iaculis sem. Etiam at aliquam est. Praesent ut sem elit. Vestibulum condimentum sem molestie lectus faucibus, vel condimentum tellus dignissim. Maecenas dictum fringilla accumsan. Aliquam id lorem elementum dui tempor ultrices quis molestie ipsum. Cras blandit porttitor arcu, vel congue enim pellentesque quis. Ut vitae ante nisl. Vestibulum malesuada suscipit magna et sodales. Quisque posuere, leo non viverra finibus, est eros aliquet quam, sit amet interdum dui nunc sed purus. Mauris aliquet, enim a laoreet egestas, orci dolor scelerisque massa, vel pulvinar dui turpis a ipsum. Nullam accumsan leo nulla, sed dignissim leo tincidunt vitae. Maecenas vitae tristique massa. Donec molestie metus in elit hendrerit imperdiet. Vestibulum id ultrices lacus, ut ultrices libero.
    
    Vestibulum facilisis nisl libero, sit amet consectetur diam vestibulum quis. Donec molestie vulputate risus at fermentum. Etiam egestas accumsan augue, sit amet tempor diam. Quisque tristique libero quis ante faucibus, ac feugiat orci faucibus. Nullam dignissim finibus sem vitae ornare. Suspendisse vulputate sem at nisl tincidunt, eu venenatis lorem pellentesque. Aenean et nulla est. Quisque mollis ligula faucibus, rhoncus mauris in, efficitur purus. Quisque in turpis nunc. Aliquam posuere congue libero quis tempor. Nunc a orci ut sem posuere mattis in quis sem. Etiam accumsan ligula eu ligula maximus, ac placerat eros tincidunt. Aenean tempor arcu finibus nisl tempor commodo. Vivamus nec arcu sed turpis gravida pharetra vulputate suscipit dolor. Vivamus sit amet congue libero.
    
    Sed vulputate lorem eget libero suscipit sodales. Suspendisse faucibus vehicula elit non iaculis. Suspendisse eros diam, cursus ac nibh vitae, vehicula sagittis ligula. Suspendisse vulputate mauris sed nunc tempus hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin accumsan, risus sed tristique aliquet, erat leo facilisis augue, nec bibendum neque urna sed velit. Suspendisse et erat turpis. Curabitur a dapibus lorem, sed rutrum mauris. Nullam mauris felis, feugiat id aliquet a, consectetur eu felis. Sed iaculis in nisl ullamcorper tristique. Curabitur quis lectus blandit, varius orci ac, blandit magna. Curabitur condimentum congue diam scelerisque suscipit. Mauris ac neque a lorem vehicula sodales. Suspendisse tempus vehicula purus. Nullam tellus sapien, tristique sit amet odio eu, elementum viverra velit. Integer maximus tortor in mollis lobortis.
    
    Donec interdum felis id ex pretium facilisis. Vestibulum facilisis vestibulum egestas. Sed et erat id neque dapibus dictum non vitae risus. Suspendisse a ligula vitae justo commodo efficitur in placerat nisi. Pellentesque ac facilisis nulla. Vestibulum blandit eros et sem viverra egestas. Nunc lorem lorem, posuere semper ullamcorper quis, porta quis nulla. Etiam facilisis arcu eget tortor commodo, sit amet mollis elit egestas. Sed semper, nunc at aliquam fringilla, sapien dui eleifend urna, eu suscipit urna urna id lectus. Etiam porttitor elementum massa, eget iaculis dolor feugiat quis. Nunc maximus malesuada feugiat. Sed tempor pulvinar odio, sed maximus quam tristique at. Ut accumsan dictum cursus. Quisque tempor pretium ultricies.</div>
  )
}

export default Dashboard